repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    - id: pyupgrade
- repo: local
  hooks:
  - id: ruff-lint
    name: Ruff
    entry: make lint
    language: system
    types: [python]
- repo: local
  hooks:
  - id: ruff-format
    name: Ruff
    entry: make format
    language: system
    types: [python]
- repo: local
  hooks:
  - id: pyright
    name: Pyright
    entry: make check/types
    language: system
    types: [python]
- repo: local
  hooks:
  - id: typos
    name: Typos
    entry: make check/spell
    language: system
    types: [python]
